#include "./ErrorHelper.hpp"
using namespace CubA4::render::vulkan::util;

std::string ErrorHelper::getResultString(VkResult result) const
{
	#define HANDLE_RESULT(r) case r: return #r;
	switch (result)
	{
		HANDLE_RESULT(VK_SUCCESS)
		HANDLE_RESULT(VK_NOT_READY)
		HANDLE_RESULT(VK_TIMEOUT)
		HANDLE_RESULT(VK_EVENT_SET)
		HANDLE_RESULT(VK_EVENT_RESET)
		HANDLE_RESULT(VK_INCOMPLETE)
		HANDLE_RESULT(VK_ERROR_OUT_OF_HOST_MEMORY)
		HANDLE_RESULT(VK_ERROR_OUT_OF_DEVICE_MEMORY)
		HANDLE_RESULT(VK_ERROR_INITIALIZATION_FAILED)
		HANDLE_RESULT(VK_ERROR_DEVICE_LOST)
		HANDLE_RESULT(VK_ERROR_MEMORY_MAP_FAILED)
		HANDLE_RESULT(VK_ERROR_LAYER_NOT_PRESENT)
		HANDLE_RESULT(VK_ERROR_EXTENSION_NOT_PRESENT)
		HANDLE_RESULT(VK_ERROR_FEATURE_NOT_PRESENT)
		HANDLE_RESULT(VK_ERROR_INCOMPATIBLE_DRIVER)
		HANDLE_RESULT(VK_ERROR_TOO_MANY_OBJECTS)
		HANDLE_RESULT(VK_ERROR_FORMAT_NOT_SUPPORTED)
		HANDLE_RESULT(VK_ERROR_FRAGMENTED_POOL)
		HANDLE_RESULT(VK_ERROR_OUT_OF_POOL_MEMORY)
		HANDLE_RESULT(VK_ERROR_INVALID_EXTERNAL_HANDLE)
		HANDLE_RESULT(VK_ERROR_SURFACE_LOST_KHR)
		HANDLE_RESULT(VK_ERROR_NATIVE_WINDOW_IN_USE_KHR)
		HANDLE_RESULT(VK_SUBOPTIMAL_KHR)
		HANDLE_RESULT(VK_ERROR_OUT_OF_DATE_KHR)
		HANDLE_RESULT(VK_ERROR_INCOMPATIBLE_DISPLAY_KHR)
		HANDLE_RESULT(VK_ERROR_VALIDATION_FAILED_EXT)
		HANDLE_RESULT(VK_ERROR_INVALID_SHADER_NV)
		HANDLE_RESULT(VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT)
		HANDLE_RESULT(VK_ERROR_FRAGMENTATION_EXT)
		HANDLE_RESULT(VK_ERROR_NOT_PERMITTED_EXT)
		default:
			return "[UNKNOWN]";
	}
	#undef HANDLE_RESULT
}