cmake_minimum_required (VERSION 2.8)

if (CMAKE_SIZEOF_VOID_P EQUAL 8)
	set (TARGET_ARCH x64 )
else ()
	set (TARGET_ARCH x86 )
endif ()

if (MSVC)
	set(SOURCE_GROUP_SEP "\\")
	set(SOURCE_GROUP_HEADER_START "Header Files\\")
	set(SOURCE_GROUP_SOURCE_START "Source Files\\")
else()
	set(SOURCE_GROUP_SEP "/")
	set(SOURCE_GROUP_HEADER_START "")
	set(SOURCE_GROUP_SOURCE_START "")
endif ()