#ifndef MODLOADER_MOD_LOADER_LIBRARY_HPP
#define MODLOADER_MOD_LOADER_LIBRARY_HPP

#ifndef MODLOADER_LIBRARY_IMPORT_EXPORT_DECLARATIONS
#define MODLOADER_LIBRARY_IMPORT_EXPORT_DECLARATIONS

#if defined (_MSC_VER) || defined(__MINGW32)
#define LIBRARY_EXPORT __declspec(dllexport) 
#define LIBRARY_IMPORT __declspec(dllimport)
#else
#define LIBRARY_EXPORT __attribute__((visibility("default")))
#define LIBRARY_IMPORT __attribute__((visibility("default")))
#endif

#endif // MODLOADER_LIBRARY_IMPORT_EXPORT_DECLARATIONS

#ifdef MOD_LOADER_LIBRARY
#define MOD_LOADER_SHARED LIBRARY_EXPORT
#else // MOD_LOADER_LIBRARY
#define MOD_LOADER_SHARED LIBRARY_IMPORT
#endif // MODLOADER_MOD_LOADER_LIBRARY

#endif // MODLOADER_MOD_LOADER_LIBRARY_HPP