#include "./ButtonAdapter.hpp"
using namespace CubA4::controls;
using namespace CubA4::game::controller;

#define CUBA4_ADAPT_BTN_TO_SDL(CBTN, SDL_BTN) case CBTN: return SDL_BTN 
#define CUBA4_ADAPT_BTN_FROM_SDL(CBTN, SDL_BTN) case SDL_BTN: return CBTN 

SDL_Scancode ButtonAdapter::adapt(Button button)
{
	switch (button)
	{
	CUBA4_ADAPT_BTN_TO_SDL(Button::N0, SDL_SCANCODE_0);
	CUBA4_ADAPT_BTN_TO_SDL(Button::N1, SDL_SCANCODE_1);
	CUBA4_ADAPT_BTN_TO_SDL(Button::N2, SDL_SCANCODE_2);
	CUBA4_ADAPT_BTN_TO_SDL(Button::N3, SDL_SCANCODE_3);
	CUBA4_ADAPT_BTN_TO_SDL(Button::N4, SDL_SCANCODE_4);
	CUBA4_ADAPT_BTN_TO_SDL(Button::N5, SDL_SCANCODE_5);
	CUBA4_ADAPT_BTN_TO_SDL(Button::N6, SDL_SCANCODE_6);
	CUBA4_ADAPT_BTN_TO_SDL(Button::N7, SDL_SCANCODE_7);
	CUBA4_ADAPT_BTN_TO_SDL(Button::N8, SDL_SCANCODE_8);
	CUBA4_ADAPT_BTN_TO_SDL(Button::N9, SDL_SCANCODE_9);
	CUBA4_ADAPT_BTN_TO_SDL(Button::A, SDL_SCANCODE_A);
	CUBA4_ADAPT_BTN_TO_SDL(Button::B, SDL_SCANCODE_B);
	CUBA4_ADAPT_BTN_TO_SDL(Button::C, SDL_SCANCODE_C);
	CUBA4_ADAPT_BTN_TO_SDL(Button::D, SDL_SCANCODE_D);
	CUBA4_ADAPT_BTN_TO_SDL(Button::E, SDL_SCANCODE_E);
	CUBA4_ADAPT_BTN_TO_SDL(Button::F, SDL_SCANCODE_F);
	CUBA4_ADAPT_BTN_TO_SDL(Button::G, SDL_SCANCODE_G);
	CUBA4_ADAPT_BTN_TO_SDL(Button::H, SDL_SCANCODE_H);
	CUBA4_ADAPT_BTN_TO_SDL(Button::I, SDL_SCANCODE_I);
	CUBA4_ADAPT_BTN_TO_SDL(Button::J, SDL_SCANCODE_J);
	CUBA4_ADAPT_BTN_TO_SDL(Button::K, SDL_SCANCODE_K);
	CUBA4_ADAPT_BTN_TO_SDL(Button::L, SDL_SCANCODE_L);
	CUBA4_ADAPT_BTN_TO_SDL(Button::M, SDL_SCANCODE_M);
	CUBA4_ADAPT_BTN_TO_SDL(Button::N, SDL_SCANCODE_N);
	CUBA4_ADAPT_BTN_TO_SDL(Button::O, SDL_SCANCODE_O);
	CUBA4_ADAPT_BTN_TO_SDL(Button::P, SDL_SCANCODE_P);
	CUBA4_ADAPT_BTN_TO_SDL(Button::Q, SDL_SCANCODE_Q);
	CUBA4_ADAPT_BTN_TO_SDL(Button::R, SDL_SCANCODE_R);
	CUBA4_ADAPT_BTN_TO_SDL(Button::S, SDL_SCANCODE_S);
	CUBA4_ADAPT_BTN_TO_SDL(Button::T, SDL_SCANCODE_T);
	CUBA4_ADAPT_BTN_TO_SDL(Button::U, SDL_SCANCODE_U);
	CUBA4_ADAPT_BTN_TO_SDL(Button::V, SDL_SCANCODE_V);
	CUBA4_ADAPT_BTN_TO_SDL(Button::W, SDL_SCANCODE_W);
	CUBA4_ADAPT_BTN_TO_SDL(Button::X, SDL_SCANCODE_X);
	CUBA4_ADAPT_BTN_TO_SDL(Button::Y, SDL_SCANCODE_Y);
	CUBA4_ADAPT_BTN_TO_SDL(Button::Z, SDL_SCANCODE_Z);
	CUBA4_ADAPT_BTN_TO_SDL(Button::ALeft, SDL_SCANCODE_LEFT);
	CUBA4_ADAPT_BTN_TO_SDL(Button::ARight, SDL_SCANCODE_RIGHT);
	CUBA4_ADAPT_BTN_TO_SDL(Button::AUp, SDL_SCANCODE_UP);
	CUBA4_ADAPT_BTN_TO_SDL(Button::ADown, SDL_SCANCODE_DOWN);
	CUBA4_ADAPT_BTN_TO_SDL(Button::Space, SDL_SCANCODE_SPACE);
	CUBA4_ADAPT_BTN_TO_SDL(Button::Enter, SDL_SCANCODE_RETURN);
	CUBA4_ADAPT_BTN_TO_SDL(Button::Backspace, SDL_SCANCODE_BACKSPACE);
	CUBA4_ADAPT_BTN_TO_SDL(Button::Escape, SDL_SCANCODE_ESCAPE);
	CUBA4_ADAPT_BTN_TO_SDL(Button::Tab, SDL_SCANCODE_TAB);
	CUBA4_ADAPT_BTN_TO_SDL(Button::F1, SDL_SCANCODE_F1);
	CUBA4_ADAPT_BTN_TO_SDL(Button::F2, SDL_SCANCODE_F2);
	CUBA4_ADAPT_BTN_TO_SDL(Button::F3, SDL_SCANCODE_F3);
	CUBA4_ADAPT_BTN_TO_SDL(Button::F4, SDL_SCANCODE_F4);
	CUBA4_ADAPT_BTN_TO_SDL(Button::F5, SDL_SCANCODE_F5);
	CUBA4_ADAPT_BTN_TO_SDL(Button::F6, SDL_SCANCODE_F6);
	CUBA4_ADAPT_BTN_TO_SDL(Button::F7, SDL_SCANCODE_F7);
	CUBA4_ADAPT_BTN_TO_SDL(Button::F8, SDL_SCANCODE_F8);
	CUBA4_ADAPT_BTN_TO_SDL(Button::F9, SDL_SCANCODE_F9);
	CUBA4_ADAPT_BTN_TO_SDL(Button::F10, SDL_SCANCODE_F10);
	CUBA4_ADAPT_BTN_TO_SDL(Button::F11, SDL_SCANCODE_F11);
	CUBA4_ADAPT_BTN_TO_SDL(Button::F12, SDL_SCANCODE_F12);
	}
	return SDL_SCANCODE_UNKNOWN;
}

CubA4::game::controller::Button ButtonAdapter::adapt(SDL_Scancode scancode)
{
	switch (scancode)
	{
	CUBA4_ADAPT_BTN_FROM_SDL(Button::N0, SDL_SCANCODE_0);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::N1, SDL_SCANCODE_1);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::N2, SDL_SCANCODE_2);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::N3, SDL_SCANCODE_3);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::N4, SDL_SCANCODE_4);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::N5, SDL_SCANCODE_5);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::N6, SDL_SCANCODE_6);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::N7, SDL_SCANCODE_7);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::N8, SDL_SCANCODE_8);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::N9, SDL_SCANCODE_9);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::A, SDL_SCANCODE_A);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::B, SDL_SCANCODE_B);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::C, SDL_SCANCODE_C);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::D, SDL_SCANCODE_D);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::E, SDL_SCANCODE_E);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::F, SDL_SCANCODE_F);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::G, SDL_SCANCODE_G);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::H, SDL_SCANCODE_H);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::I, SDL_SCANCODE_I);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::J, SDL_SCANCODE_J);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::K, SDL_SCANCODE_K);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::L, SDL_SCANCODE_L);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::M, SDL_SCANCODE_M);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::N, SDL_SCANCODE_N);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::O, SDL_SCANCODE_O);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::P, SDL_SCANCODE_P);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::Q, SDL_SCANCODE_Q);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::R, SDL_SCANCODE_R);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::S, SDL_SCANCODE_S);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::T, SDL_SCANCODE_T);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::U, SDL_SCANCODE_U);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::V, SDL_SCANCODE_V);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::W, SDL_SCANCODE_W);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::X, SDL_SCANCODE_X);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::Y, SDL_SCANCODE_Y);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::Z, SDL_SCANCODE_Z);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::ALeft, SDL_SCANCODE_LEFT);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::ARight, SDL_SCANCODE_RIGHT);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::AUp, SDL_SCANCODE_UP);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::ADown, SDL_SCANCODE_DOWN);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::Space, SDL_SCANCODE_SPACE);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::Enter, SDL_SCANCODE_RETURN);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::Backspace, SDL_SCANCODE_BACKSPACE);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::Escape, SDL_SCANCODE_ESCAPE);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::Tab, SDL_SCANCODE_TAB);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::F1, SDL_SCANCODE_F1);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::F2, SDL_SCANCODE_F2);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::F3, SDL_SCANCODE_F3);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::F4, SDL_SCANCODE_F4);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::F5, SDL_SCANCODE_F5);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::F6, SDL_SCANCODE_F6);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::F7, SDL_SCANCODE_F7);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::F8, SDL_SCANCODE_F8);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::F9, SDL_SCANCODE_F9);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::F10, SDL_SCANCODE_F10);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::F11, SDL_SCANCODE_F11);
	CUBA4_ADAPT_BTN_FROM_SDL(Button::F12, SDL_SCANCODE_F12);
	}
	return Button::None;
}

CubA4::game::controller::Button ButtonAdapter::adaptMouse(uint8_t btn)
{
	switch (btn)
	{
	case SDL_BUTTON_LEFT:
		return Button::LMB;
	case SDL_BUTTON_RIGHT:
		return Button::RMB;
	case SDL_BUTTON_MIDDLE:
		return Button::MMB;
	}
	return Button::None;
}

BMods ButtonAdapter::adapt(uint16_t mod)
{
	BMods mods {};
	mods |= (mod & SDL_Keymod::KMOD_LALT) ? BMod::LAlt : BMod::None;
	mods |= (mod & SDL_Keymod::KMOD_RALT) ? BMod::RAlt : BMod::None;
	mods |= (mod & SDL_Keymod::KMOD_LCTRL) ? BMod::LCtrl : BMod::None;
	mods |= (mod & SDL_Keymod::KMOD_RCTRL) ? BMod::RCtrl : BMod::None;
	mods |= (mod & SDL_Keymod::KMOD_LSHIFT) ? BMod::LShift : BMod::None;
	mods |= (mod & SDL_Keymod::KMOD_RSHIFT) ? BMod::RShift : BMod::None;
	return mods;
}