set(CUBA4_ROOT_RUNTIME_DIR ${CUBA4_PROJECT_DIR}/built/$<CONFIG>/)

set(BIN_BUILD_OUTPUT_DIRECTORY ${CUBA4_ROOT_RUNTIME_DIR}/bin)
set(MOD_BUILD_OUTPUT_DIRECTORY ${CUBA4_ROOT_RUNTIME_DIR}/mods)
set(RENDER_BUILD_OUTPUT_DIRECTORY ${CUBA4_ROOT_RUNTIME_DIR}/render)
set(RESOURCES_OUTPUT_DIRECTORY ${CUBA4_ROOT_RUNTIME_DIR}/data)

set(BUILD_OUTPUT_DIRECTORY ${BIN_BUILD_OUTPUT_DIRECTORY})